### ISSUE TITLE
Error:  No usable value for personResult

### ISSUE THREAD

**Issue by Nechanicky** [ok-dobris/TeamResults#3]
Ahoj, dnes jsme pořádali Přebor škol ZR a chtěl jsem využít výpočet výsledů. 
Bohužel mi to vrací chybu 'No usable value for personResult'.
Netuším co to může způsobit. 
Jedná se o závod https://oris.orientacnisporty.cz/Vysledky?id=7884
Díky moc za odpověď, abych věděl, čemu se napříště vyhnout.
Pavel N OSN7209

**Comment by OndrejSpanel** [comment]
Problém dělá kategorie H3, ve které je jen jeden závodník. Odhaduji, že příčinou je chyba knihovny `json4s`.

Pokusím se to nějak obejít nebo vyřešit.

**Comment by OndrejSpanel** [comment]
Nedokonalý převod dat z XML selhal u kategorií s jediným závodníkem, json4s za nic nemohla. Nová veze https://github.com/ok-dobris/TeamResults/releases/tag/value_arrays to má opravené.

**Comment by Nechanicky** [comment]
Ahoj, 

Děkuji mnohokrát. 

Pavel N.
